### ISSUE TITLE
Search field: activate word suggestions in virtual keyboard

### ISSUE THREAD

**Issue by Pohli** [Wunderfitz/harbour-wunderfitz#28]
See title.
Or is there any reason that there should be no word suggestions?

Jolla Phone with SFOS 3.0.1.11 and Wunderfitz 1.3.1

**Comment by Wunderfitz** [comment]
I'd say this question needs go go to Jolla directly. They explicitly disabled predictive text inputs in their SearchField Silica component which is used here in Wunderfitz.

Therefore, I need to close this issue.

Thanks for your understanding and best regards, Sebastian

**Comment by Wunderfitz** [comment]
Sorry, just saw that there is an option to override Jolla's settings. Fixed with e2c66a6f3fa63187578da9ac84c7693063aee8ba.

**Comment by Pohli** [comment]
Thanks, it's working now!
