### ISSUE TITLE
Implement UI for removing imported dictionaries

### ISSUE THREAD

**Issue by Pohli** [Wunderfitz/harbour-wunderfitz#31]
After two years I just wanted a newer version of the EN-DE dictionary but now I have two imported, the older DE-EN and the new EN-DE dictionary, taking up storage.

Jolla Phone with SFOS 3.0.1.11 and Wunderfitz 1.4

**Comment by Wunderfitz** [comment]
This feature is already there - please use the pulley menu on the dictionaries page...

**Comment by Pohli** [comment]
Oh, I'm sorry! I don't know how I could've missed that.
