### ISSUE TITLE
Dictionary selection not fully accessible

### ISSUE THREAD

**Issue by Pohli** [Wunderfitz/harbour-wunderfitz#32]
On the default page (not on Dictionaries' page) I can only access the dictionary at the bottom of the list. The others are hidden beyond the upper edge. Maybe it's due to my outdated SFOS version?

Jolla Phone with SFOS 3.0.1.11 and Wunderfitz 1.4

**Comment by Wunderfitz** [comment]
Possible that it's due to the outdated version, please update to the most recent one and if you still face the problem, please include a screenshot as well.

**Comment by Wunderfitz** [comment]
No updates since over a year - closing... Please create a new issue if it comes up in a recent SFOS version.
