### ISSUE TITLE
Deactivate left/right swipe when typing in search

### ISSUE THREAD

**Issue by Pohli** [Wunderfitz/harbour-wunderfitz#35]
I can't move the cursor when typing in the search box. Instead the whole screen moves away for Curiosity feature.

Jolla Phone with SFOS 3.0.1.11 and Wunderfitz 1.4

**Comment by Pohli** [comment]
Later I could move the cursor normally, so I had a closer look: If I tap the search box and type a search term consisting of one or more words the last word will be underlined and the behaviour described in initial post will occur. But as soon as I tap into the search box again to set the cursor somewhere moving the cursor works as usual. Then I compared with other apps, I tried search functions of Jolla Store and Storeman. There the cursor is always movable but nothing's underlined. Then I tried native SMS app and began to type a message. The last word is also underlined but cursor is always movable. So something must be different in Wunderfitz.

**Comment by Wunderfitz** [comment]
The reason is the word suggestions support in the search field which you requested in #28. The word that can be corrected by the feature is always underlined. If you want to move your cursor, you need to deactivate the autocorrect mode for the respective word by tapping once on it. The word will no longer be underlined and you can move the cursor as before.

**Comment by Pohli** [comment]
Okay, but, as I already described above, in Messages app from Jolla the last word is also underlined and word suggestions are present but cursor is movable, no need to tap somewhere again, just try it. I guess Messages app is not open source?

**Comment by Wunderfitz** [comment]
The QML of Jolla's apps can usually be read though the actual backend is closed source. The difference is probably that the Messages app doesn't use a SlideshowView (the component which enables the carousel mode).
