### ISSUE TITLE
Camera fails to take picture in Curiosity mode

### ISSUE THREAD

**Issue by llewelld** [Wunderfitz/harbour-wunderfitz#40]
When taking a photo in Curiosity mode, the viewfinder works as expected. However, when pressing the button to take a shot, the app shows a spinner and the photo never gets processed. The following error is output to the log:

```
[W] CameraBinSession::processBusMessage:1102 - CameraBin error: "GStreamer encountered a general supporting library error."
```

See [the discussion](https://github.com/Wunderfitz/harbour-wunderfitz/pull/38#issuecomment-934835317) on PR#38 for more context.

After discussing this with @jpetrell, it seems it may be due to Wunderfitz not handling the state changes of the camera "correctly". As an app developer, it shouldn't be necessary to follow these state changes so carefully (the `Camera` component should "just work"), but in practice due to the vagaries of GStreamer things aren't so simple.

We now have an internal bug about making the `Camera` component more robust to these kinds of issues, but in the meantime you may find you can get things to work by following the Example Camera App in the [SDK 3.6 release](https://forum.sailfishos.org/t/release-notes-sailfish-sdk-3-6-early-access/8418) (currently in Early Access).

**Comment by Wunderfitz** [comment]
Thanks for asking @llewelld and for the hint @jpetrell, that motivated me to experiment a bit. As the example from the SDK didn't include anything special with respect to state handling, I thought it must have been something I do differently. And it was rather simple: I made `VideoOutput` invisible while the camera was still doing things. If I keep it visible, everybody seems to be happy... Commit ecb5afb32c018f0b479b75f39471e3fcfa84cc16 seems to fix the issue.
