### ISSUE TITLE
Case sensitivity for umlauts

### ISSUE THREAD

**Issue by DarthMax** [Wunderfitz/harbour-wunderfitz#5]
Hey there!

It seems that the search is case sensitive when it comes to umlauts
For instance when using the dict.cc DE/SV dictionary

Searching for `Ödmjuk` yields no results while searching for `ödmjuk` does
However when I search for `Rolig` I get the same results as for `rolig`

PS: Thanks for this great App :)

**Comment by Wunderfitz** [comment]
Hi there,

thanks for reporting that. I can also reproduce it for other languages. As soon as I have some time, I'll look into it and fix it.

Regards, Sebastian

**Comment by DarthMax** [comment]
Hi!

I think I have found a solution. The key is to change the tokenizer for the `entries` table like this

`CREATE VIRTUAL TABLE my_entries using fts4(id integer primary key, left_word text, category text, ..., tokenize=unicode61 "remove_diacritics=0");`

This tokenizer seems to know how to handle umlauts and so on. The `remove_diacritics=0` tells the tokenizer to not convert umlauts etc into "normal" letters.

**Comment by Wunderfitz** [comment]
Thanks again! Really disappointing that the currently used SQLite Porter stemmer completely ignores Non-ASCII characters when it comes to automated lowercase conversion... However, moving away from Porter might have some disadvantages for queries in English...

Anyway, most certainly I'll do that. But I need to do some testing before the next release. If nothing happens, I'll have something ready until next week. :)

**Comment by Wunderfitz** [comment]
Version 0.5 including the fix is released. Now available from OpenRepos https://openrepos.net/content/ygriega/wunderfitz and most certainly soon in Jolla Store.
