### ISSUE TITLE
Some translate not shipped in v-1.0

### ISSUE THREAD

**Issue by Caballlero** [Wunderfitz/harbour-wunderfitz#8]
Only the line 72 not shipped . = ) also i looking for translators name strings of words to do a fix, but this words are not included in *.es.ts.

**Comment by Wunderfitz** [comment]
Sorry that I didn't reply earlier. I missed the e-mail notification obviously...
Could it be that you use the OpenRepos version? I noticed that I missed some translation updates for the very first version, but updated it for the Jolla Store... There, all translations should be there.

**Comment by Caballlero** [comment]
OK ...
I do not have any update from "jolla_store", i mainly use ( "warehouse app", i have installed v-1.0-1 ).
- Can you add: " translator name " sentences. Because no exist. or fix my name in " translator name " you put carlos gonzales and is carlos gonzalez  =  ) 
- Line 72 are not shipped in  -v 1.0-1 in warehouse, will check jolla_store.

**Comment by Wunderfitz** [comment]
Well, translating the names of people would be weird, don't you think? ;) 
Sorry, that your name wasn't spelled correctly. I changed it and also published a new build to OpenRepos. 1.0-3 should contain the corrected name. :)

**Comment by Caballlero** [comment]
Well , i say add " translator name "sentences to modify. Not to translate.  =  ) just to try fix my case.
Although I could also send you a PR by modifying AboutPage.qml where the sentence is located, but I do not remember that. I apologize  =  ) THANKS ALL IS FIXED ...
