### ISSUE TITLE
Feature Request:   add wunderfitz version in wuderfitz_about page.

### ISSUE THREAD

**Issue by Caballlero** [Wunderfitz/harbour-wunderfitz#9]
Is usefull to see the current version thank you ...

**Comment by Wunderfitz** [comment]
The major version (0.3, or currently 1) is already displayed in the About page. However, I won't include the build number (the one behind the -) there as this is normally only to show the different development iterations.

**Comment by Caballlero** [comment]
- Here is why i asked about put wunderfitz version.  In the way this one does not notice the version. It would be better to look like this: v 1.0.3 below Wunderfitz would look much better and clear.  
                                                               Wunderfitz
                                                                  v  1.0.3
- Current look

![20170611094347](https://user-images.githubusercontent.com/24536606/27011523-388d0f0e-4e8b-11e7-8b9a-6ab1c4f40215.jpg)

**Comment by Caballlero** [comment]
- What you thing dev ?

**Comment by Wunderfitz** [comment]
I understood your request and it will stay as it is and as I mentioned in my first reply. the major and minor version will be in the about page, the build number not. So you'll get 1.1 or 2.4 but not 1.0-3 (see the difference between 1.0-3 and 1.0.3... The build number is normally only an indicator for me for development iterations - the release of several builds is an exception as I forgot to add some translations.

**Comment by Caballlero** [comment]
sebastian you are confusing me, can you share what you know about digit of versions ? because to me is 3 digit . like "  0.0.0 - major.minor.micro " and release digit to developer use.

**Comment by Wunderfitz** [comment]
I simply don't use such a micro version. So my builds will always have major.minor-build.

**Comment by Caballlero** [comment]
Thank you: but in the picture only show major digit ,that make or make me a confusion.
